services:
  db:
    image: postgres:9.5
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    image: ecommerce
    restart: always
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8888:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
